name: sponge_grpc_client_dart
description: Sponge gRPC client for Dart. It simplifies connecting to a remote Sponge gRPC service.
homepage: https://github.com/softelnet/sponge_grpc_client_dart
version: 1.17.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.0.0
  sync: ^0.3.0
  fixnum: ^1.0.0
  meta: ^1.7.0
  logging: ^1.0.1

  sponge_client_dart: ^1.17.0

dependency_overrides:
  # Use the local library if possible.
  sponge_client_dart:
    path: ../sponge_client_dart

dev_dependencies:
  test: ^1.17.12
  pedantic: ^1.11.1
  collection: ^1.15.0
