name: sponge_grpc_client_dart
description: Sponge gRPC client for Dart. It simplifies connecting to a remote Sponge gRPC service.
homepage: https://github.com/softelnet/sponge_grpc_client_dart
version: 1.17.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  grpc: ^2.9.0
  protobuf: ^1.1.3
  sync: ^0.2.0
  fixnum: ^0.10.11
  meta: ^1.1.8
  logging: ^0.11.4
  sponge_client_dart:
    ^1.17.0 # Uncomment for publishing.
    #path: ../sponge_client_dart # Use the local library if possible. Comment for publishing.

dev_dependencies:
  test: ^1.15.3
  pedantic: ^1.9.0
  collection: ^1.14.12
